DELIMITER //
DROP PROCEDURE IF EXISTS AVERAGE_LINKS;
CREATE PROCEDURE AVERAGE_LINKS()
BEGIN
SELECT AVG(UserLinks.LinkCount) AS AVG_LINK_COUNT
FROM (SELECT e1.UserId, COUNT(DISTINCT (cl1.Link)) AS LinkCount
FROM Enrollment e1 NATURAL JOIN (Course c1 NATURAL JOIN CourseLink cl1)
GROUP BY e1.UserId) AS UserLinks ;
END //
DELIMITER ;
