DELIMITER //
DROP PROCEDURE IF EXISTS AVERAGE_EVENTS;
CREATE PROCEDURE AVERAGE_EVENTS()
BEGIN
SELECT AVG(UserEvents.EventCount) AS AVG_EVENT_COUNT
FROM (SELECT ce1.UserId, c1.CourseId, COUNT(e1.EventId) AS EventCount
FROM CreateEvent ce1 NATURAL JOIN (Event e1 NATURAL JOIN (Assign a1 NATURAL JOIN Course c1))
GROUP BY ce1.UserId,c1.CourseId) AS UserEvents ;
END //
DELIMITER ;
