DELIMITER //

CREATE OR REPLACE PROCEDURE DELETE_DATA() 

BEGIN
DELETE FROM User ;
DELETE FROM Event ;
DELETE FROM Account ;
DELETE FROM CourseLink ;
DELETE FROM Enrollment ;
DELETE FROM CreateEvent ;
DELETE FROM Course ;
DELETE FROM Assign ;
END //

DELIMITER ;
