DELIMITER //
DROP PROCEDURE IF EXISTS DISPLAY_LINKS_FOR_COURSE;
CREATE PROCEDURE DISPLAY_LINKS_FOR_COURSE(
   	courseId_ INT
	 )
    BEGIN
        SELECT * 
	FROM CourseLink
	WHERE CourseId=courseId_;
    END //
DELIMITER ;
