DELIMITER //
DROP PROCEDURE IF EXISTS SHARED_CLASSES;
CREATE PROCEDURE SHARED_CLASSES(
	userID_ INT
)
BEGIN
SELECT COUNT(DISTINCT UserId)
FROM Enrollment e1 NATURAL JOIN Course c1
WHERE c1.CourseName IN 
(SELECT c2.CourseName FROM Enrollment e2 NATURAL JOIN Course c2 WHERE e2.UserId=userID_) 
AND e1.UserId <> userID_ ;
END //
DELIMITER ;
