DELIMITER //
DROP PROCEDURE IF EXISTS USER_DISPLAY;
CREATE PROCEDURE USER_DISPLAY(
   	userId_ INT
	 )
    BEGIN
        SELECT * 
	FROM Account NATURAL JOIN User
	WHERE UserId = userId_ ;
    END //
DELIMITER ;
